global:
  namespace: as-bank-dev
  environment: dev
  team: application
  costCenter: learning

  cognito:
    issuer: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_IyPZIF1zh"
    clientId: "1imfotcestj1eq7e2hlpotl77n"

  network:
    vpcCidr: 10.10.0.0/16

workloads:
  customer-service:
    enabled: true
    kind: java
    version: "728ca83b8076"

    image:
      repository: as-bank/customer-service
      digest: sha256:728ca83b80760c389691ee67bd6733960328599ee520e9f7fe5366568c8fddd5

    database:
      enabled: true
      remoteSecret: as-bank/dev/database/customer-service

    runtimeConfig:
      enabled: false

    probes:
      port: management
      startupPath: /actuator/health/liveness
      readinessPath: /actuator/health/readiness
      livenessPath: /actuator/health/liveness

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    autoscaling:
      minReplicas: 1
      maxReplicas: 2
      cpuUtilization: 70

    network:
      ingressFrom:
        - account-service
      egressTo: []
      allowHttpsEgress: true

  account-service:
    enabled: true
    kind: java
    version: "2481c56260e6"

    image:
      repository: as-bank/account-service
      digest: sha256:2481c56260e627f9b513b8240812713ed55378f1b63fcc0c917b70b6311f7a89

    database:
      enabled: true
      remoteSecret: as-bank/dev/database/account-service

    runtimeConfig:
      enabled: false

    probes:
      port: management
      startupPath: /actuator/health/liveness
      readinessPath: /actuator/health/readiness
      livenessPath: /actuator/health/liveness

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    autoscaling:
      minReplicas: 1
      maxReplicas: 2
      cpuUtilization: 70

    network:
      ingressFrom:
        - transaction-service
      egressTo:
        - customer-service
      allowHttpsEgress: true

  transaction-service:
    enabled: true
    kind: java
    version: "84446de5b9fc"

    image:
      repository: as-bank/transaction-service
      digest: sha256:84446de5b9fc93a3f4088e9790f4c151b03130e55a7ba49e44eb66c94ea45690

    database:
      enabled: true
      remoteSecret: as-bank/dev/database/transaction-service

    runtimeConfig:
      enabled: false

    probes:
      port: management
      startupPath: /actuator/health/liveness
      readinessPath: /actuator/health/readiness
      livenessPath: /actuator/health/liveness

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    autoscaling:
      minReplicas: 1
      maxReplicas: 2
      cpuUtilization: 70

    network:
      ingressFrom: []
      egressTo:
        - account-service
      allowHttpsEgress: true

  frontend:
    enabled: true
    kind: frontend
    version: "e72df72e41da"

    image:
      repository: as-bank/frontend
      digest: sha256:e72df72e41da12cefc02972384617cfd0b959353b3def795a288ce51070079a2

    database:
      enabled: false
      remoteSecret: ""

    runtimeConfig:
      enabled: true
      customerApiBaseUrl: https://api-dev.aslearnings.online
      accountApiBaseUrl: https://api-dev.aslearnings.online
      transactionApiBaseUrl: https://api-dev.aslearnings.online

    probes:
      port: http
      startupPath: /
      readinessPath: /
      livenessPath: /

    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

    autoscaling:
      minReplicas: 1
      maxReplicas: 2
      cpuUtilization: 70

    network:
      ingressFrom: []
      egressTo: []
      allowHttpsEgress: false
