global:
  namespace: as-bank-dev
  environment: dev
  team: application
  costCenter: learning

  cognito:
    issuer: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_IyPZIF1zh"
    clientId: "1imfotcestj1eq7e2hlpotl77n"

  network:
    vpcCidr: 10.10.0.0/16
    albSourceCidrs:
      - 10.10.0.0/24
      - 10.10.1.0/24
edge:
  enabled: true
  frontendHost: dev.aslearnings.online
  apiHost: api-dev.aslearnings.online

workloads:
  customer-service:
    enabled: true
    kind: java
    version: "65adc030c364"

    image:
      repository: as-bank/customer-service
      digest: sha256:40d14f3091cfc578bee8a66556ff645bfc90ab58828d3036aa097fe17466e5ad

    database:
      enabled: true
      remoteSecret: as-bank/dev/database/customer-service

    runtimeConfig:
      enabled: false

    probes:
      port: management
      startupPath: /actuator/health/liveness
      readinessPath: /actuator/health/readiness
      livenessPath: /actuator/health/liveness

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    autoscaling:
      minReplicas: 1
      maxReplicas: 2
      cpuUtilization: 70

    network:
      ingressFrom:
        - account-service
      egressTo: []
      allowHttpsEgress: true
      allowAlbIngress: true

  account-service:
    enabled: true
    kind: java
    version: "65adc030c364"

    image:
      repository: as-bank/account-service
      digest: sha256:b0e3a517968c9b512c13389dc4afad565aee6ef5e7c1637391d26ded34a471e7

    database:
      enabled: true
      remoteSecret: as-bank/dev/database/account-service

    runtimeConfig:
      enabled: false

    probes:
      port: management
      startupPath: /actuator/health/liveness
      readinessPath: /actuator/health/readiness
      livenessPath: /actuator/health/liveness

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    autoscaling:
      minReplicas: 1
      maxReplicas: 2
      cpuUtilization: 70

    network:
      ingressFrom:
        - transaction-service
      egressTo:
        - customer-service
      allowHttpsEgress: true
      allowAlbIngress: true

  transaction-service:
    enabled: true
    kind: java
    version: "65adc030c364"

    image:
      repository: as-bank/transaction-service
      digest: sha256:b8dd0374defc5858da30df7c87bfc780baf0276ecfd2a7733a7c307f88f60059

    database:
      enabled: true
      remoteSecret: as-bank/dev/database/transaction-service

    runtimeConfig:
      enabled: false

    probes:
      port: management
      startupPath: /actuator/health/liveness
      readinessPath: /actuator/health/readiness
      livenessPath: /actuator/health/liveness

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    autoscaling:
      minReplicas: 1
      maxReplicas: 2
      cpuUtilization: 70

    network:
      ingressFrom: []
      egressTo:
        - account-service
      allowHttpsEgress: true
      allowAlbIngress: true

  frontend:
    enabled: true
    kind: frontend
    version: "65adc030c364"

    image:
      repository: as-bank/frontend
      digest: sha256:b79b05a14139cabb9cff99e66429b82002ca6b7369a1fd1f9435e3e0a919dde4

    database:
      enabled: false
      remoteSecret: ""

    runtimeConfig:
      enabled: true
      customerApiBaseUrl: https://api-dev.aslearnings.online
      accountApiBaseUrl: https://api-dev.aslearnings.online
      transactionApiBaseUrl: https://api-dev.aslearnings.online

    probes:
      port: http
      startupPath: /
      readinessPath: /
      livenessPath: /

    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

    autoscaling:
      minReplicas: 1
      maxReplicas: 2
      cpuUtilization: 70

    network:
      ingressFrom: []
      egressTo: []
      allowHttpsEgress: false
      allowAlbIngress: true
