apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudfront-origin-header
  namespace: as-bank-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 5m

  secretStoreRef:
    kind: SecretStore
    name: aws-secrets-manager

  target:
    name: cloudfront-origin-header
    creationPolicy: Owner

  data:
    - secretKey: name
      remoteRef:
        key: as-bank/dev/edge/cloudfront-origin-header
        property: name

    - secretKey: value
      remoteRef:
        key: as-bank/dev/edge/cloudfront-origin-header
        property: value
